language: scala

scala:
  - "0.25.0-RC2"
  - "2.11.12"
  - "2.12.11"
  - "2.13.2"

jdk:
  - openjdk11

sudo: required
dist: trusty

env:
  - SCALAJS_VERSION=1.1.1

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.coursier
    - $HOME/.sbt

script:
  - if [[ "$TRAVIS_SCALA_VERSION" == 0.* ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION coreJVM/test;
    else
      sbt ++$TRAVIS_SCALA_VERSION fmtCheck test mimaReportBinaryIssues;
    fi

